# Generated by Django 4.2 on 2025-07-02 07:17

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="城市名"),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "城市",
                "verbose_name_plural": "城市",
            },
        ),
        migrations.CreateModel(
            name="ComputerRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="机房名称"),
                ),
                ("address", models.CharField(max_length=100, verbose_name="机房地址")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hosts.city",
                        verbose_name="所在城市",
                    ),
                ),
            ],
            options={
                "verbose_name": "机房",
                "verbose_name_plural": "机房",
                "unique_together": {("city", "name")},
            },
        ),
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="主机名称"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(unique=True, verbose_name="IP地址"),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("Windows", "Windows"),
                            ("Linux", "Linux"),
                            ("MacOS", "MacOS"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="操作系统",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "运行中"),
                            ("Fault", "故障"),
                            ("Maintenance", "维护中"),
                            ("Deactivate", "下线"),
                            ("Unknown", "未知"),
                        ],
                        max_length=20,
                        verbose_name="主机状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "computer_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hosts.computerroom",
                        verbose_name="所在机房",
                    ),
                ),
            ],
            options={
                "verbose_name": "主机",
                "verbose_name_plural": "主机",
            },
        ),
        migrations.CreateModel(
            name="HostPassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "root_password",
                    django_cryptography.fields.encrypt(
                        models.CharField(max_length=255, verbose_name="root密码")
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "expiration_time",
                    models.DateTimeField(null=True, verbose_name="密码过期时间"),
                ),
                (
                    "host",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hosts.host",
                        verbose_name="主机",
                    ),
                ),
            ],
            options={
                "verbose_name": "主机密码",
                "verbose_name_plural": "主机密码",
            },
        ),
        migrations.CreateModel(
            name="HostGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_type",
                    models.CharField(
                        choices=[("City", "城市"), ("ComputerRoom", "机房")],
                        max_length=20,
                        verbose_name="分组类型",
                    ),
                ),
                ("host_count", models.IntegerField(verbose_name="主机数量")),
                ("date", models.DateField(verbose_name="统计日期")),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hosts.city",
                        verbose_name="城市",
                    ),
                ),
                (
                    "computer_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hosts.computerroom",
                        verbose_name="机房",
                    ),
                ),
            ],
            options={
                "verbose_name": "主机统计",
                "verbose_name_plural": "主机统计",
                "unique_together": {
                    ("city", "group_type", "date"),
                    ("computer_room", "group_type", "date"),
                },
            },
        ),
    ]
